Crud1/Models/ADBcontext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MySql.Data;
using Microsoft.EntityFrameworkCore;

namespace Crud1.Models
{
    public class ADBcontext : DbContext
    {
        public ADBcontext(DbContextOptions<ADBcontext>options):base(options)
        {

        }

        public DbSet<Ninio> Ninio { get; set; }
        public DbSet<Tutor> Tutor { get; set; }
    }
}

Crud1/Models/ErrorViewModel.cs
using System;

namespace Crud1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Crud1/Models/Ninio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Crud1.Models
{
    public class Ninio
    {
        [Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required(ErrorMessage ="Campo requerido")]
        [StringLength(30,ErrorMessage ="No puede ingresar nombres mayores a 30")]
        public string nombres { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        public string apellidos { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name ="Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public DateTime fechanac { get; set; }
        public int idtutor { get; set; }

    }
}

Crud1/Models/Tutor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Crud1.Models
{
    public class Tutor
    {
        [Key]
        public int IdTutor { get; set; }
        
        [Required(ErrorMessage ="Este campo es obligatorio")]
        [Display(Name ="Nombre del Tutor")]
        [StringLength(30, ErrorMessage ="Este campo requiere menos de 30 caracteres")]
        public string nombreT { get; set; }

        public string apellidoT { get; set; }

        [DataType(DataType.Date)]
        public DateTime fechanacT { get; set; }
    }
}

Crud1/Controllers/HomeController.cs
using Crud1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Crud1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Crud1/Controllers/NiniosController.cs
using Crud1.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Crud1.Controllers
{
    public class NiniosController : Controller
    {
        private readonly ADBcontext _context;

        public NiniosController(ADBcontext context)
        {
            _context = context;
        }
        
        //get index
        public IActionResult Index()
        {
            IEnumerable<Ninio> listNinios = _context.Ninio;
            return View(listNinios);
        }

        //get create
        public IActionResult Create()
        {
            return View();
        }

        //post create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Ninio ninio)
        {
            if(ModelState.IsValid)
            {
                _context.Ninio.Add(ninio);
                _context.SaveChanges();

                TempData["mensaje"] = "El niño se ha ingresado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }

        //get edit
        public IActionResult Edit(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }

            var ninio = _context.Ninio.Find(id);

            if (ninio==null)
            {
                return NotFound();
            }

            return View(ninio);
        }
        //post editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Ninio ninio)
        {
            if (ModelState.IsValid)
            {
                _context.Ninio.Update(ninio);
                _context.SaveChanges();

                TempData["mensaje"] = "El niño se ha actualizado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }

        //get delete, asegurar que tenga el mismo nombre la vista
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var ninio = _context.Ninio.Find(id);

            if (ninio == null)
            {
                return NotFound();
            }

            return View(ninio);
        }
        //post eliminar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteN(int? id)
        {
            var ninio = _context.Ninio.Find(id);

            if (ninio == null)
            {
                return NotFound();
            } 
            
            _context.Ninio.Remove(ninio);
            _context.SaveChanges();
            
            TempData["mensaje"] = "El registro del niño se ha eliminado correctamente";
            return RedirectToAction("Index");
        }
    }
}

Crud1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Crud1/Views/Ninios/Create.cshtml
@model Crud1.Models.Ninio
@{
    ViewData["Title"] = "Crear nuevo niño";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class=" col-sm-12">
        <h3>Crear nuevo Niño</h3>
    </div>
</div>

<div class="row">
    <div class=" col-sm-10">
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombres" class="control-label"></label>
                <input asp-for="nombres" class="form-control" />
                <span asp-validation-for="nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apellidos" class="control-label"></label>
                <input asp-for="apellidos" class="form-control" />
                <span asp-validation-for="apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechanac" class="control-label"></label>
                <input asp-for="fechanac" class="form-control" />
                <span asp-validation-for="fechanac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idtutor" class="control-label"></label>
                <input asp-for="idtutor" class="form-control" />
                <span asp-validation-for="idtutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear Ninio" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
     
    @{ <partial name="_ValidationScriptsPartial" />}

 }

Crud1/Views/Ninios/Delete.cshtml
@model Crud1.Models.Ninio
@{
    ViewData["Title"] = "Eliminar el registro del niño";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    
    

    <div class="row">
        <div class=" col-sm-12">
            <h3>Eliminar el registro del Niño</h3>
        </div>
    </div>

    <div class="row">
        <div class=" col-sm-10">
            <form method="post" asp-action="DeleteN">
                <input type="hidden" asp-for="Id" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Id" class="control-label"></label>
                    <input asp-for="Id" class="form-control" disabled />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="nombres" class="control-label"></label>
                    <input asp-for="nombres" class="form-control" disabled />
                    <span asp-validation-for="nombres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="apellidos" class="control-label"></label>
                    <input asp-for="apellidos" class="form-control" disabled />
                    <span asp-validation-for="apellidos" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="fechanac" class="control-label"></label>
                    <input asp-for="fechanac" class="form-control" disabled />
                    <span asp-validation-for="fechanac" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="idtutor" class="control-label"></label>
                    <input asp-for="idtutor" class="form-control" disabled />
                    <span asp-validation-for="idtutor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Eliminar registro del niño" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts{
     
    @{ <partial name="_ValidationScriptsPartial" />}

 }

Crud1/Views/Ninios/Edit.cshtml
@model Crud1.Models.Ninio
@{
    ViewData["Title"] = "Crear nuevo niño";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    
    

    <div class="row">
        <div class=" col-sm-12">
            <h3>Editar Niño</h3>
        </div>
    </div>

    <div class="row">
        <div class=" col-sm-10">
            <form method="post" asp-action="Edit">
                <input type="hidden" asp-for="Id" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Id" class="control-label"></label>
                    <input asp-for="Id" class="form-control" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="nombres" class="control-label"></label>
                    <input asp-for="nombres" class="form-control" />
                    <span asp-validation-for="nombres" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="apellidos" class="control-label"></label>
                    <input asp-for="apellidos" class="form-control" />
                    <span asp-validation-for="apellidos" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="fechanac" class="control-label"></label>
                    <input asp-for="fechanac" class="form-control" />
                    <span asp-validation-for="fechanac" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="idtutor" class="control-label"></label>
                    <input asp-for="idtutor" class="form-control" />
                    <span asp-validation-for="idtutor" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Editar Niño" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts{
     
    @{ <partial name="_ValidationScriptsPartial" />}

 }

Crud1/Views/Ninios/Index.cshtml
@model IEnumerable<Crud1.Models.Ninio>
@{
    ViewData["Title"] = "Lista de Niños";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    @if(TempData["mensaje"]!= null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @TempData["mensaje"];
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">
        <div class=" col-sm-6">
            <h3>Lista de Niños</h3>
        </div>
        <div class=" col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Ninios">Agregar Niños</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(n => n.Id)</td>
                        <td>@Html.DisplayNameFor(n => n.nombres)</td>
                        <td>@Html.DisplayNameFor(n => n.apellidos)</td>
                        <td>@Html.DisplayNameFor(n => n.fechanac)</td>
                        <td>@Html.DisplayNameFor(n => n.idtutor)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in Model)
                    {
                        <tr>
                            <td>@x.Id</td>
                            <td>@x.nombres}</td>
                            <td>@x.apellidos</td>
                            <td>@x.fechanac</td>
                            <td>@x.idtutor</td>
                            <td>
                                <a asp-controller="Ninios" asp-action="Edit" asp-route-id="@x.Id" class="btn btn-warning">Editar</a>
                                <a asp-controller="Ninios" asp-action="Delete" asp-route-id="@x.Id" class="btn btn-danger">Eliminar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No existen registros</p>
        }
    </div>
</div>

Crud1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crud1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Crud1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ninios" asp-action="Index">Crud Niños</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tutor" asp-action="Index">Crud Tutor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Crud1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>